# Autogenerated wrapper script for codon_linux_jll for x86_64-linux-gnu-cxx03
export codon_linux, libcodonc, libcodonrt, libomp

JLLWrappers.@generate_wrapper_header("codon_linux")
JLLWrappers.@declare_library_product(libcodonc, "libcodonc.so")
JLLWrappers.@declare_library_product(libcodonrt, "libcodonrt.so")
JLLWrappers.@declare_library_product(libomp, "libomp.so")
JLLWrappers.@declare_executable_product(codon_linux)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcodonc,
        "lib/libcodonc.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcodonrt,
        "lib/libcodonrt.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libomp,
        "lib/libomp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        codon_linux,
        "bin/codon",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
